version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      volumes:
        - ./brecho_luz_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: brecho_luz
        POSTGRES_USER: br3ch0_luz
        POSTGRES_PASSWORD: "17142522"
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: brecho_luz
        DB_USER: br3ch0_luz
        DB_SCHEMA: public
        DB_PASSWORD: "17142522"
        KEYCLOAK_USER: brecho_luz
        KEYCLOAK_PASSWORD: "17142522"
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 8080:8080
      depends_on:
        - postgres